site_name: RoundBox
repo_url: https://github.com/soulraven/roundbox
site_url: https://soulraven.github.io/roundbox
site_description: A small lightweight framework for IoT applications
site_author: Zaharia Constantin
copyright: Maintained by <a href="https://progeek.ro">SoulRaven</a>.
site_dir: "site"
edit_uri: ""

watch:
  - README.md

nav:
  - Home: index.md
  - User Guide:
      #- user-guide/topics/index.md
      - Install: user-guide/topics/install.md
      - Settings: user-guide/topics/settings.md
      - Signals: user-guide/topics/signals.md
      - Schedule: user-guide/topics/jobs_scheduling.md
  - Releases:
      - releases/index.md
      - 0.9: releases/0.9.md
      - 1.0: releases/1.0.md
  #- Developer Guide:
  - About:
      - Credits: credits.md
      - Libraries: libraries.md
      - License: license.md
  - FAQ: faq/index.md
      #- Install: faq/install.md
#  - Code Reference: reference/
#  - Dev:
#    - Coverage report: coverage.md
  - Author's website: https://soulraven.github.io/

plugins:
  - search
#  - coverage
  - gen-files:
      scripts:
      - docs/gen_credits.py
      - docs/gen_ref_nav.py
  #- autolinks
  - awesome-pages
  - pagenav-generator
  - tags
  - literate-nav:
      nav_file: SUMMARY.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/soulraven
      name: SoulRaven Github Profile

markdown_extensions:
  - admonition
  - sane_lists
  - def_list
  - attr_list
  - md_in_html
  - meta
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.saneheaders
#  - toc:
#      permalink: true
#      toc_depth: 1
  - pymdownx.arithmatex:
      generic: true

