site_name: RoundBox
repo_url: https://github.com/soulraven/roundbox
site_url: https://soulraven.github.io/roundbox
site_description: A small lightweight framework for IoT applications
site_author: Zaharia Constantin
copyright: Maintained by <a href="https://progeek.ro">SoulRaven</a>.

nav:
  - Home: index.md
  - Jobs: jobs/jobs_scheduling.md
plugins:
  - search

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue

extra:
  generator: false

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
